# Generated by Django 5.2.9 on 2026-01-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0002_nationaltarget_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
