# Generated by Django 5.2.9 on 2026-01-14 13:49

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0003_organisation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationaltarget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_national_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='national_targets', to='nbms_app.organisation'),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='sensitivity',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicator',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='nbms_app.organisation'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='sensitivity',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
