# Generated by Django 5.2.9 on 2026-01-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0004_add_abac_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='review_note',
            field=models.TextField(blank=True),
        ),
    ]
