# Generated by Django 5.2.9 on 2026-01-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0007_notification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['status'], name='nbms_app_in_status_635344_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['sensitivity'], name='nbms_app_in_sensiti_8588a7_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['organisation'], name='nbms_app_in_organis_fd6e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['created_by'], name='nbms_app_in_created_0e8c28_idx'),
        ),
        migrations.AddIndex(
            model_name='nationaltarget',
            index=models.Index(fields=['status'], name='nbms_app_na_status_28819f_idx'),
        ),
        migrations.AddIndex(
            model_name='nationaltarget',
            index=models.Index(fields=['sensitivity'], name='nbms_app_na_sensiti_099e21_idx'),
        ),
        migrations.AddIndex(
            model_name='nationaltarget',
            index=models.Index(fields=['organisation'], name='nbms_app_na_organis_a12e17_idx'),
        ),
        migrations.AddIndex(
            model_name='nationaltarget',
            index=models.Index(fields=['created_by'], name='nbms_app_na_created_031d9c_idx'),
        ),
    ]
