# Generated by Django 5.2.9 on 2026-01-14 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0012_instanceexportapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportpackage',
            name='reporting_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_packages', to='nbms_app.reportinginstance'),
        ),
    ]
