# Generated by Django 5.2.9 on 2026-01-15 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0014_consentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordering', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ReportSectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('reporting_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_responses', to='nbms_app.reportinginstance')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_section_responses', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='nbms_app.reportsectiontemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reporting_instance', 'template'), name='uq_report_section_response')],
            },
        ),
    ]
