# Generated by Django 5.2.9 on 2026-01-20 16:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0016_validationruleset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='public', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_frameworks', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frameworks', to='nbms_app.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='public', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_framework_indicators', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='nbms_app.framework')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framework_indicators', to='nbms_app.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='public', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_framework_targets', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='nbms_app.framework')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framework_targets', to='nbms_app.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorFrameworkIndicatorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('equivalent', 'Equivalent'), ('contributes_to', 'Contributes to'), ('partial', 'Partial'), ('supports', 'Supports')], default='contributes_to', max_length=50)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('source', models.URLField(blank=True)),
                ('framework_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_indicator_links', to='nbms_app.frameworkindicator')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_indicator_links', to='nbms_app.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='NationalTargetFrameworkTargetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('equivalent', 'Equivalent'), ('contributes_to', 'Contributes to'), ('partial', 'Partial'), ('supports', 'Supports')], default='contributes_to', max_length=50)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('source', models.URLField(blank=True)),
                ('framework_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_target_links', to='nbms_app.frameworktarget')),
                ('national_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_target_links', to='nbms_app.nationaltarget')),
            ],
        ),
        migrations.AddIndex(
            model_name='framework',
            index=models.Index(fields=['status'], name='nbms_app_fr_status_2efaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='framework',
            index=models.Index(fields=['sensitivity'], name='nbms_app_fr_sensiti_fd7b90_idx'),
        ),
        migrations.AddIndex(
            model_name='framework',
            index=models.Index(fields=['organisation'], name='nbms_app_fr_organis_fcb548_idx'),
        ),
        migrations.AddIndex(
            model_name='framework',
            index=models.Index(fields=['created_by'], name='nbms_app_fr_created_588fad_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworkindicator',
            index=models.Index(fields=['status'], name='nbms_app_fr_status_dec17c_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworkindicator',
            index=models.Index(fields=['sensitivity'], name='nbms_app_fr_sensiti_d1a9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworkindicator',
            index=models.Index(fields=['organisation'], name='nbms_app_fr_organis_68a9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworkindicator',
            index=models.Index(fields=['created_by'], name='nbms_app_fr_created_607fc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='frameworkindicator',
            constraint=models.UniqueConstraint(fields=('framework', 'code'), name='uq_framework_indicator'),
        ),
        migrations.AddIndex(
            model_name='frameworktarget',
            index=models.Index(fields=['status'], name='nbms_app_fr_status_52080e_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworktarget',
            index=models.Index(fields=['sensitivity'], name='nbms_app_fr_sensiti_f8870d_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworktarget',
            index=models.Index(fields=['organisation'], name='nbms_app_fr_organis_6a962e_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworktarget',
            index=models.Index(fields=['created_by'], name='nbms_app_fr_created_6b894f_idx'),
        ),
        migrations.AddConstraint(
            model_name='frameworktarget',
            constraint=models.UniqueConstraint(fields=('framework', 'code'), name='uq_framework_target'),
        ),
        migrations.AddConstraint(
            model_name='indicatorframeworkindicatorlink',
            constraint=models.UniqueConstraint(fields=('indicator', 'framework_indicator'), name='uq_indicator_framework_indicator'),
        ),
        migrations.AddConstraint(
            model_name='nationaltargetframeworktargetlink',
            constraint=models.UniqueConstraint(fields=('national_target', 'framework_target'), name='uq_national_target_framework_target'),
        ),
    ]
