# Generated by Django 5.2.9 on 2026-01-20 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0018_frameworkindicator_indicator_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionIIINationalTargetProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('progress_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('partially_achieved', 'Partially achieved'), ('achieved', 'Achieved'), ('unknown', 'Unknown')], default='not_started', max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('actions_taken', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('support_needed', models.TextField(blank=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('binary_indicator_responses', models.ManyToManyField(blank=True, related_name='section_iii_progress_entries', to='nbms_app.binaryindicatorresponse')),
                ('dataset_releases', models.ManyToManyField(blank=True, related_name='section_iii_progress_entries', to='nbms_app.datasetrelease')),
                ('evidence_items', models.ManyToManyField(blank=True, related_name='section_iii_progress_entries', to='nbms_app.evidence')),
                ('indicator_data_series', models.ManyToManyField(blank=True, related_name='section_iii_progress_entries', to='nbms_app.indicatordataseries')),
                ('national_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_iii_progress_entries', to='nbms_app.nationaltarget')),
                ('reporting_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_iii_progress_entries', to='nbms_app.reportinginstance')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reporting_instance', 'national_target'), name='uq_section_iii_progress')],
            },
        ),
        migrations.CreateModel(
            name='SectionIVFrameworkTargetProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('progress_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('partially_achieved', 'Partially achieved'), ('achieved', 'Achieved'), ('unknown', 'Unknown')], default='not_started', max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('actions_taken', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('support_needed', models.TextField(blank=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('binary_indicator_responses', models.ManyToManyField(blank=True, related_name='section_iv_progress_entries', to='nbms_app.binaryindicatorresponse')),
                ('dataset_releases', models.ManyToManyField(blank=True, related_name='section_iv_progress_entries', to='nbms_app.datasetrelease')),
                ('evidence_items', models.ManyToManyField(blank=True, related_name='section_iv_progress_entries', to='nbms_app.evidence')),
                ('framework_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_iv_progress_entries', to='nbms_app.frameworktarget')),
                ('indicator_data_series', models.ManyToManyField(blank=True, related_name='section_iv_progress_entries', to='nbms_app.indicatordataseries')),
                ('reporting_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_iv_progress_entries', to='nbms_app.reportinginstance')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reporting_instance', 'framework_target'), name='uq_section_iv_progress')],
            },
        ),
    ]
