# Generated by Django 5.2.9 on 2026-01-22 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0020_reportingsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('changes_requested', 'Changes requested')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_review_decisions', to=settings.AUTH_USER_MODEL)),
                ('reporting_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='nbms_app.reportinginstance')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='nbms_app.reportingsnapshot')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='nbms_app.reviewdecision')),
            ],
            options={
                'indexes': [models.Index(fields=['reporting_instance', 'created_at'], name='nbms_app_re_reporti_fb7d1c_idx')],
            },
        ),
    ]
