# Generated by Django 5.2.9 on 2026-01-28 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_audit_event_type(apps, schema_editor):
    AuditEvent = apps.get_model("nbms_app", "AuditEvent")
    for event in AuditEvent.objects.filter(event_type=""):
        event.event_type = event.action or ""
        event.save(update_fields=["event_type"])


def _backfill_framework_goal_status(apps, schema_editor):
    FrameworkGoal = apps.get_model("nbms_app", "FrameworkGoal")
    FrameworkGoal.objects.filter(is_active=False).update(status="archived")


def _backfill_methodology_version_links(apps, schema_editor):
    MethodologyIndicatorLink = apps.get_model("nbms_app", "MethodologyIndicatorLink")
    MethodologyVersion = apps.get_model("nbms_app", "MethodologyVersion")
    IndicatorMethodologyVersionLink = apps.get_model("nbms_app", "IndicatorMethodologyVersionLink")

    for link in MethodologyIndicatorLink.objects.all():
        versions = MethodologyVersion.objects.filter(methodology_id=link.methodology_id, is_active=True)
        if versions.count() != 1:
            continue
        version = versions.first()
        IndicatorMethodologyVersionLink.objects.get_or_create(
            indicator_id=link.indicator_id,
            methodology_version_id=version.id,
            defaults={
                "is_primary": False,
                "notes": link.notes or "",
                "is_active": getattr(link, "is_active", True),
            },
        )

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nbms_app', '0025_license_sourcedocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('system_admin', 'System Admin access')]},
        ),
        migrations.AddField(
            model_name='auditevent',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='object_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_method',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='session_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(_backfill_audit_event_type, migrations.RunPython.noop),
        migrations.AddField(
            model_name='frameworkgoal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_framework_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frameworkgoal',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framework_goals', to='nbms_app.organisation'),
        ),
        migrations.AddField(
            model_name='frameworkgoal',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='frameworkgoal',
            name='sensitivity',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='frameworkgoal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20),
        ),
        migrations.RunPython(_backfill_framework_goal_status, migrations.RunPython.noop),
        migrations.AddField(
            model_name='indicator',
            name='computation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='data_steward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stewarded_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(choices=[('headline', 'Headline'), ('binary', 'Binary'), ('component', 'Component'), ('complementary', 'Complementary'), ('national', 'National'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='nbms_app.license'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='limitations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='qa_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('validated', 'Validated'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='reporting_cadence',
            field=models.CharField(blank=True, choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('ad_hoc', 'Ad hoc'), ('continuous', 'Continuous')], max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='responsible_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_indicators', to='nbms_app.organisation'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='nbms_app.sourcedocument'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='source_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='indicator',
            name='source_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='indicator',
            name='spatial_coverage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='temporal_coverage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indicatorframeworkindicatorlink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='national_targets', to='nbms_app.license'),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='provenance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='qa_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('validated', 'Validated'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='reporting_cadence',
            field=models.CharField(blank=True, choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('ad_hoc', 'Ad hoc'), ('continuous', 'Continuous')], max_length=20),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='responsible_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_national_targets', to='nbms_app.organisation'),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='national_targets', to='nbms_app.sourcedocument'),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='source_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='source_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='spatial_coverage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nationaltarget',
            name='temporal_coverage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nationaltargetframeworktargetlink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='object_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='object_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IndicatorMethodologyVersionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('source', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodology_version_links', to='nbms_app.indicator')),
                ('methodology_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_links', to='nbms_app.methodologyversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('indicator', 'methodology_version'), name='uq_indicator_methodology_version')],
            },
        ),
        migrations.RunPython(_backfill_methodology_version_links, migrations.RunPython.noop),
    ]
