# Generated by Django 5.2.9 on 2026-01-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nbms_app', '0026_alter_user_options_auditevent_content_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['created_at'], name='idx_audit_created_at'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type', 'created_at'], name='idx_audit_event_type_created'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'created_at'], name='idx_audit_actor_created'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_audit_content_object'),
        ),
    ]
