# Generated by Django 5.2.9 on 2026-02-02 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0026_alter_user_options_auditevent_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binaryindicatorquestion',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_questions', to='nbms_app.binaryindicatorquestion'),
        ),
        migrations.AddField(
            model_name='sectioniiinationaltargetprogress',
            name='challenges_and_approaches',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sectioniiinationaltargetprogress',
            name='effectiveness_examples',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sectioniiinationaltargetprogress',
            name='progress_level',
            field=models.CharField(choices=[('on_track', 'On track'), ('insufficient_rate', 'Insufficient rate'), ('no_change', 'No change'), ('not_applicable', 'Not applicable'), ('unknown', 'Unknown'), ('achieved', 'Achieved')], default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='sectioniiinationaltargetprogress',
            name='sdg_and_other_agreements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sectionivframeworktargetprogress',
            name='challenges_and_approaches',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sectionivframeworktargetprogress',
            name='effectiveness_examples',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sectionivframeworktargetprogress',
            name='progress_level',
            field=models.CharField(choices=[('on_track', 'On track'), ('insufficient_rate', 'Insufficient rate'), ('no_change', 'No change'), ('not_applicable', 'Not applicable'), ('unknown', 'Unknown'), ('achieved', 'Achieved')], default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='sectionivframeworktargetprogress',
            name='sdg_and_other_agreements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='binaryindicatorquestion',
            name='question_type',
            field=models.CharField(choices=[('option', 'Option'), ('checkbox', 'Checkbox'), ('header', 'Header'), ('string', 'String')], default='option', max_length=20),
        ),
        migrations.CreateModel(
            name='BinaryIndicatorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('target_code', models.CharField(blank=True, max_length=50)),
                ('binary_indicator_code', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('framework_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binary_indicator_groups', to='nbms_app.frameworkindicator')),
                ('framework_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binary_indicator_groups', to='nbms_app.frameworktarget')),
            ],
        ),
        migrations.AddField(
            model_name='binaryindicatorquestion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='nbms_app.binaryindicatorgroup'),
        ),
        migrations.CreateModel(
            name='BinaryIndicatorGroupResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('comments', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='nbms_app.binaryindicatorgroup')),
                ('reporting_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binary_indicator_group_responses', to='nbms_app.reportinginstance')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binary_indicator_group_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionIINBSAPStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nbsap_updated_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('in_progress', 'In progress'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('nbsap_updated_other_text', models.TextField(blank=True)),
                ('nbsap_expected_completion_date', models.DateField(blank=True, null=True)),
                ('stakeholders_involved', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('stakeholder_groups', models.JSONField(blank=True, default=list)),
                ('stakeholder_groups_other_text', models.TextField(blank=True)),
                ('stakeholder_groups_notes', models.TextField(blank=True)),
                ('nbsap_adopted_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('in_progress', 'In progress'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('nbsap_adopted_other_text', models.TextField(blank=True)),
                ('nbsap_adoption_mechanism', models.TextField(blank=True)),
                ('nbsap_expected_adoption_date', models.DateField(blank=True, null=True)),
                ('monitoring_system_description', models.TextField()),
                ('reporting_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_ii_status', to='nbms_app.reportinginstance')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_ii_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionIReportContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporting_party_name', models.CharField(max_length=255)),
                ('submission_language', models.CharField(max_length=64)),
                ('additional_languages', models.JSONField(blank=True, default=list)),
                ('responsible_authorities', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('preparation_process', models.TextField(blank=True)),
                ('preparation_challenges', models.TextField(blank=True)),
                ('acknowledgements', models.TextField(blank=True)),
                ('reporting_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_i_context', to='nbms_app.reportinginstance')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_i_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionIVFrameworkGoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('progress_summary', models.TextField()),
                ('actions_taken', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('challenges_and_approaches', models.TextField(blank=True)),
                ('sdg_and_other_agreements', models.TextField(blank=True)),
                ('evidence_items', models.ManyToManyField(blank=True, related_name='section_iv_goal_progress_entries', to='nbms_app.evidence')),
                ('framework_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_iv_progress_entries', to='nbms_app.frameworkgoal')),
                ('reporting_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_iv_goal_progress_entries', to='nbms_app.reportinginstance')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_iv_goal_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionVConclusions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_assessment', models.TextField()),
                ('decision_15_8_information', models.TextField(blank=True)),
                ('decision_15_7_information', models.TextField(blank=True)),
                ('decision_15_11_information', models.TextField(blank=True)),
                ('plant_conservation_information', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('evidence_items', models.ManyToManyField(blank=True, related_name='section_v_conclusions', to='nbms_app.evidence')),
                ('reporting_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_v_conclusions', to='nbms_app.reportinginstance')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_v_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='binaryindicatorgroup',
            index=models.Index(fields=['framework_target'], name='nbms_app_bi_framewo_f0a37b_idx'),
        ),
        migrations.AddIndex(
            model_name='binaryindicatorgroup',
            index=models.Index(fields=['framework_indicator'], name='nbms_app_bi_framewo_0291b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='binaryindicatorgroupresponse',
            constraint=models.UniqueConstraint(fields=('reporting_instance', 'group'), name='uq_binary_indicator_group_response'),
        ),
        migrations.AddConstraint(
            model_name='sectionivframeworkgoalprogress',
            constraint=models.UniqueConstraint(fields=('reporting_instance', 'framework_goal'), name='uq_section_iv_goal_progress'),
        ),
    ]
