# Generated by Django 5.2.9 on 2026-02-02 11:19

from django.db import migrations, models


def map_question_types(apps, schema_editor):
    BinaryIndicatorQuestion = apps.get_model("nbms_app", "BinaryIndicatorQuestion")
    mapping = {
        "option": "single",
        "checkbox": "multiple",
        "string": "text",
        "header": "text",
    }
    for old_value, new_value in mapping.items():
        BinaryIndicatorQuestion.objects.filter(question_type=old_value).update(question_type=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0027_binaryindicatorquestion_parent_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binaryindicatorquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='binaryindicatorquestion',
            name='validations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(map_question_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='binaryindicatorquestion',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple'), ('text', 'Text')], default='single', max_length=20),
        ),
    ]
