# Generated by Django 5.2.9 on 2026-02-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0028_binaryindicatorquestion_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='coverage_geography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='coverage_time_end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='coverage_time_start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='data_quality_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='last_updated_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='owner_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_indicators', to='nbms_app.organisation'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='reporting_capability',
            field=models.CharField(choices=[('yes', 'Yes'), ('partial', 'Partial'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='reporting_no_reason_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='indicator',
            name='reporting_no_reason_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='update_frequency',
            field=models.CharField(blank=True, choices=[('continuous', 'Continuous'), ('annual', 'Annual'), ('biennial', 'Biennial'), ('every_3_years', 'Every 3 years'), ('ad_hoc', 'Ad hoc'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
