# Generated by Django 5.2.9 on 2026-02-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0029_indicator_coverage_geography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='reporting_capability',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('partial', 'Partial'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
