# Generated by Django 5.2.9 on 2026-02-06 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0030_alter_indicator_reporting_capability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplatePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('mea_code', models.CharField(max_length=50)),
                ('version', models.CharField(default='v1', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('export_handler', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_packs', to='nbms_app.framework')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplatePackSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='nbms_app.reporttemplatepack')),
            ],
            options={
                'ordering': ['pack__code', 'ordering', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplatePackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('reporting_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_pack_responses', to='nbms_app.reportinginstance')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_pack_responses', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='nbms_app.reporttemplatepacksection')),
            ],
        ),
        migrations.CreateModel(
            name='SpatialLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('static', 'Static'), ('indicator', 'Indicator')], default='static', max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='public', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_style_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spatial_layers', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spatial_layers', to='nbms_app.indicator')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spatial_layers', to='nbms_app.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='SpatialFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('feature_key', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('province_code', models.CharField(blank=True, max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('properties_json', models.JSONField(blank=True, default=dict)),
                ('geometry_json', models.JSONField(blank=True, default=dict)),
                ('minx', models.FloatField(blank=True, null=True)),
                ('miny', models.FloatField(blank=True, null=True)),
                ('maxx', models.FloatField(blank=True, null=True)),
                ('maxy', models.FloatField(blank=True, null=True)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spatial_features', to='nbms_app.indicator')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='nbms_app.spatiallayer')),
            ],
        ),
        migrations.AddIndex(
            model_name='reporttemplatepack',
            index=models.Index(fields=['code'], name='nbms_app_re_code_3555e9_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplatepack',
            index=models.Index(fields=['mea_code', 'is_active'], name='nbms_app_re_mea_cod_0f13a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplatepacksection',
            constraint=models.UniqueConstraint(fields=('pack', 'code'), name='uq_template_pack_section_code'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplatepackresponse',
            constraint=models.UniqueConstraint(fields=('reporting_instance', 'section'), name='uq_template_pack_response'),
        ),
        migrations.AddIndex(
            model_name='spatiallayer',
            index=models.Index(fields=['slug'], name='nbms_app_sp_slug_12e140_idx'),
        ),
        migrations.AddIndex(
            model_name='spatiallayer',
            index=models.Index(fields=['is_active', 'is_public'], name='nbms_app_sp_is_acti_b4cd44_idx'),
        ),
        migrations.AddIndex(
            model_name='spatiallayer',
            index=models.Index(fields=['sensitivity'], name='nbms_app_sp_sensiti_f0de2f_idx'),
        ),
        migrations.AddIndex(
            model_name='spatiallayer',
            index=models.Index(fields=['organisation'], name='nbms_app_sp_organis_1a11c8_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialfeature',
            index=models.Index(fields=['layer', 'feature_key'], name='nbms_app_sp_layer_i_1e987b_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialfeature',
            index=models.Index(fields=['province_code'], name='nbms_app_sp_provinc_e08761_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialfeature',
            index=models.Index(fields=['year'], name='nbms_app_sp_year_712069_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialfeature',
            index=models.Index(fields=['indicator'], name='nbms_app_sp_indicat_af50b6_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialfeature',
            index=models.Index(fields=['minx', 'maxx'], name='nbms_app_sp_minx_c5d09c_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialfeature',
            index=models.Index(fields=['miny', 'maxy'], name='nbms_app_sp_miny_16f28f_idx'),
        ),
        migrations.AddConstraint(
            model_name='spatialfeature',
            constraint=models.UniqueConstraint(fields=('layer', 'feature_key'), name='uq_spatial_feature_layer_key'),
        ),
    ]
