# Generated by Django 5.2.9 on 2026-02-06 23:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0031_reporttemplatepack_reporttemplatepacksection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringprogramme',
            name='data_quality_rules_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monitoringprogramme',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringprogramme',
            name='lineage_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monitoringprogramme',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringprogramme',
            name='operating_institutions',
            field=models.ManyToManyField(blank=True, related_name='operating_monitoring_programmes', to='nbms_app.organisation'),
        ),
        migrations.AddField(
            model_name='monitoringprogramme',
            name='pipeline_definition_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monitoringprogramme',
            name='refresh_cadence',
            field=models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('ad_hoc', 'Ad hoc')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='monitoringprogramme',
            name='scheduler_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MonitoringProgrammeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('run_type', models.CharField(choices=[('full', 'Full'), ('ingest', 'Ingest'), ('validate', 'Validate'), ('compute', 'Compute'), ('publish', 'Publish')], default='full', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('integration', 'Integration')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_summary_json', models.JSONField(blank=True, default=dict)),
                ('output_summary_json', models.JSONField(blank=True, default=dict)),
                ('artifacts_json', models.JSONField(blank=True, default=list)),
                ('lineage_json', models.JSONField(blank=True, default=dict)),
                ('log_excerpt', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='nbms_app.monitoringprogramme')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_programme_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringProgrammeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('state', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('code', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programme_alerts', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='nbms_app.monitoringprogramme')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_programme_alerts', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='nbms_app.monitoringprogrammerun')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringProgrammeRunStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('step_key', models.CharField(max_length=50)),
                ('step_type', models.CharField(choices=[('ingest', 'Ingest'), ('validate', 'Validate'), ('compute', 'Compute'), ('publish', 'Publish')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('log_excerpt', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='nbms_app.monitoringprogrammerun')),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringProgrammeSteward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('steward', 'Steward'), ('operator', 'Operator'), ('reviewer', 'Reviewer')], default='steward', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steward_assignments', to='nbms_app.monitoringprogramme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_programme_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='monitoringprogramme',
            name='stewards',
            field=models.ManyToManyField(blank=True, related_name='stewarded_monitoring_programmes', through='nbms_app.MonitoringProgrammeSteward', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammerun',
            index=models.Index(fields=['programme', 'created_at'], name='nbms_app_mo_program_dc0155_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammerun',
            index=models.Index(fields=['programme', 'status'], name='nbms_app_mo_program_c6f0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammerun',
            index=models.Index(fields=['status', 'created_at'], name='nbms_app_mo_status_3bbdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammerun',
            index=models.Index(fields=['run_type'], name='nbms_app_mo_run_typ_100b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammealert',
            index=models.Index(fields=['programme', 'state'], name='nbms_app_mo_program_97169d_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammealert',
            index=models.Index(fields=['programme', 'severity'], name='nbms_app_mo_program_d8e31c_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammealert',
            index=models.Index(fields=['created_at'], name='nbms_app_mo_created_f1b85b_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammerunstep',
            index=models.Index(fields=['run', 'ordering'], name='nbms_app_mo_run_id_180ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammerunstep',
            index=models.Index(fields=['status'], name='nbms_app_mo_status_55cf40_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitoringprogrammerunstep',
            constraint=models.UniqueConstraint(fields=('run', 'ordering'), name='uq_programme_run_step_ordering'),
        ),
        migrations.AddConstraint(
            model_name='monitoringprogrammerunstep',
            constraint=models.UniqueConstraint(fields=('run', 'step_key'), name='uq_programme_run_step_key'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammesteward',
            index=models.Index(fields=['programme', 'is_active'], name='nbms_app_mo_program_afd459_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammesteward',
            index=models.Index(fields=['user', 'is_active'], name='nbms_app_mo_user_id_66e00e_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammesteward',
            index=models.Index(fields=['role'], name='nbms_app_mo_role_743ad2_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitoringprogrammesteward',
            constraint=models.UniqueConstraint(fields=('programme', 'user', 'role'), name='uq_programme_steward_assignment'),
        ),
    ]
