# Generated by Django 5.2.9 on 2026-02-07 00:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0032_monitoringprogramme_data_quality_rules_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorMethodProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('method_type', models.CharField(choices=[('manual', 'Manual'), ('csv_import', 'CSV import'), ('api_connector', 'API connector'), ('scripted_python', 'Scripted Python'), ('scripted_r_container', 'Scripted R container'), ('spatial_overlay', 'Spatial overlay'), ('seea_accounting', 'SEEA accounting'), ('binary_questionnaire', 'Binary questionnaire')], max_length=40)),
                ('implementation_key', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('required_inputs_json', models.JSONField(blank=True, default=list)),
                ('disaggregation_requirements_json', models.JSONField(blank=True, default=list)),
                ('output_schema_json', models.JSONField(blank=True, default=dict)),
                ('readiness_state', models.CharField(choices=[('ready', 'Ready'), ('partial', 'Partial'), ('blocked', 'Blocked')], default='blocked', max_length=20)),
                ('readiness_notes', models.TextField(blank=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_system', models.CharField(blank=True, max_length=100)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_profiles', to='nbms_app.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorMethodRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='blocked', max_length=20)),
                ('parameters_json', models.JSONField(blank=True, default=dict)),
                ('input_hash', models.CharField(blank=True, max_length=128)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='nbms_app.indicatormethodprofile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_method_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='indicatormethodprofile',
            index=models.Index(fields=['method_type', 'is_active'], name='nbms_app_in_method__e3a13d_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatormethodprofile',
            index=models.Index(fields=['readiness_state'], name='nbms_app_in_readine_d457e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='indicatormethodprofile',
            constraint=models.UniqueConstraint(fields=('indicator', 'method_type', 'implementation_key'), name='uq_indicator_method_profile'),
        ),
        migrations.AddIndex(
            model_name='indicatormethodrun',
            index=models.Index(fields=['profile', 'created_at'], name='nbms_app_in_profile_bba689_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatormethodrun',
            index=models.Index(fields=['status'], name='nbms_app_in_status_4d5b02_idx'),
        ),
    ]
