# Generated by Django 5.2.9 on 2026-02-07 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0033_indicatormethodprofile_indicatormethodrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdieSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('site_code', models.CharField(max_length=80, unique=True)),
                ('site_name', models.CharField(max_length=255)),
                ('province_code', models.CharField(blank=True, max_length=20)),
                ('convention_type', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_restricted', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['site_code'],
            },
        ),
        migrations.CreateModel(
            name='BirdieSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('species_code', models.CharField(max_length=80, unique=True)),
                ('common_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(blank=True, max_length=255)),
                ('guild', models.CharField(blank=True, max_length=120)),
                ('is_restricted', models.BooleanField(default=False)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['species_code'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationDataAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_system', models.CharField(max_length=80)),
                ('layer', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=20)),
                ('dataset_key', models.CharField(max_length=120)),
                ('record_key', models.CharField(max_length=160)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('source_endpoint', models.CharField(blank=True, max_length=255)),
                ('source_version', models.CharField(blank=True, max_length=80)),
                ('is_restricted', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['source_system', 'layer'], name='nbms_app_in_source__f3b69a_idx'), models.Index(fields=['dataset_key', 'record_key'], name='nbms_app_in_dataset_0f6101_idx'), models.Index(fields=['is_restricted'], name='nbms_app_in_is_rest_ea840a_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'layer', 'dataset_key', 'record_key'), name='uq_integration_asset_record')],
            },
        ),
        migrations.CreateModel(
            name='ReportProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(default='v1', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('export_handler', models.CharField(blank=True, max_length=120)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='nbms_app_re_code_377f18_idx'), models.Index(fields=['is_active'], name='nbms_app_re_is_acti_b9dcf7_idx')],
            },
        ),
        migrations.CreateModel(
            name='BirdieModelOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('metric_code', models.CharField(max_length=80)),
                ('year', models.PositiveIntegerField()),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('value_text', models.TextField(blank=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('model_version', models.CharField(blank=True, max_length=80)),
                ('provenance_json', models.JSONField(blank=True, default=dict)),
                ('is_restricted', models.BooleanField(default=False)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birdie_outputs', to='nbms_app.indicator')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='nbms_app.birdiesite')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='nbms_app.birdiespecies')),
            ],
            options={
                'ordering': ['metric_code', 'year', 'id'],
                'indexes': [models.Index(fields=['metric_code', 'year'], name='nbms_app_bi_metric__42e147_idx'), models.Index(fields=['site', 'year'], name='nbms_app_bi_site_id_228e40_idx'), models.Index(fields=['indicator', 'year'], name='nbms_app_bi_indicat_22cdee_idx')],
                'constraints': [models.UniqueConstraint(fields=('species', 'site', 'metric_code', 'year'), name='uq_birdie_output_row')],
            },
        ),
        migrations.CreateModel(
            name='ReportProductRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('failed', 'Failed'), ('published', 'Published')], default='draft', max_length=20)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('html_content', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_product_runs', to=settings.AUTH_USER_MODEL)),
                ('reporting_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_product_runs', to='nbms_app.reportinginstance')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='nbms_app.reportproducttemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['template', 'created_at'], name='nbms_app_re_templat_1859dc_idx'), models.Index(fields=['status', 'created_at'], name='nbms_app_re_status_eee101_idx')],
            },
        ),
    ]
