# Generated by Django 5.2.9 on 2026-02-08 08:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0035_spatialunit_spatialunittype_dataset_dataset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatiallayer',
            name='geoserver_layer_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='spatiallayer',
            name='publish_to_geoserver',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MonitoringProgrammeArtefactRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('storage_path', models.CharField(max_length=512)),
                ('media_type', models.CharField(blank=True, max_length=120)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artefacts', to='nbms_app.monitoringprogrammerun')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefacts', to='nbms_app.monitoringprogrammerunstep')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringProgrammeQAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warn', 'Warn'), ('fail', 'Fail')], default='pass', max_length=20)),
                ('message', models.TextField()),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_results', to='nbms_app.monitoringprogrammerun')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_results', to='nbms_app.monitoringprogrammerunstep')),
            ],
        ),
        migrations.CreateModel(
            name='SpatialSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField()),
                ('source_format', models.CharField(choices=[('GeoJSON', 'GeoJSON'), ('GPKG', 'GeoPackage'), ('ESRI Shapefile', 'ESRI Shapefile'), ('ZIP_ESRI_SHP', 'ZIP Shapefile'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('source_layer_name', models.CharField(blank=True, max_length=255)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('attribution', models.CharField(blank=True, max_length=255)),
                ('terms_url', models.URLField(blank=True)),
                ('requires_token', models.BooleanField(default=False)),
                ('token_env_var', models.CharField(blank=True, max_length=120)),
                ('update_frequency', models.CharField(blank=True, choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('ad_hoc', 'Ad hoc'), ('continuous', 'Continuous')], max_length=20)),
                ('enabled_by_default', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_type', models.CharField(choices=[('NBMS_TABLE', 'NBMS table'), ('UPLOADED_FILE', 'Uploaded file'), ('EXTERNAL_WMS', 'External WMS'), ('EXTERNAL_WFS', 'External WFS'), ('EXTERNAL_STAC', 'External STAC'), ('EXTERNAL_TILE', 'External tile'), ('static', 'Static (legacy)'), ('indicator', 'Indicator (legacy)')], default='UPLOADED_FILE', max_length=30)),
                ('layer_code', models.CharField(max_length=100, unique=True)),
                ('layer_title', models.CharField(blank=True, max_length=255)),
                ('layer_description', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, max_length=60)),
                ('default_style_json', models.JSONField(blank=True, default=dict)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='public', max_length=20)),
                ('consent_required', models.BooleanField(default=False)),
                ('export_approved', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('publish_to_geoserver', models.BooleanField(default=True)),
                ('expected_checksum', models.CharField(blank=True, max_length=64)),
                ('clip_bbox', models.CharField(blank=True, max_length=120)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_checksum', models.CharField(blank=True, max_length=64)),
                ('last_status', models.CharField(choices=[('ready', 'Ready'), ('skipped', 'Skipped'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='ready', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_feature_count', models.PositiveIntegerField(default=0)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spatial_sources', to='nbms_app.indicator')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spatial_sources', to='nbms_app.organisation')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorInputRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('disaggregation_expectations_json', models.JSONField(blank=True, default=dict)),
                ('cadence', models.CharField(blank=True, choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('ad_hoc', 'Ad hoc'), ('continuous', 'Continuous')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input_requirement', to='nbms_app.indicator')),
                ('required_map_layers', models.ManyToManyField(blank=True, related_name='indicator_input_requirements', to='nbms_app.spatiallayer')),
                ('required_map_sources', models.ManyToManyField(blank=True, related_name='indicator_input_requirements', to='nbms_app.spatialsource')),
            ],
        ),
        migrations.AddField(
            model_name='spatialingestionrun',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_runs', to='nbms_app.spatialsource'),
        ),
        migrations.AddField(
            model_name='spatiallayer',
            name='spatial_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers', to='nbms_app.spatialsource'),
        ),
        migrations.AddIndex(
            model_name='spatialingestionrun',
            index=models.Index(fields=['source', 'created_at'], name='nbms_app_sp_source__270f33_idx'),
        ),
        migrations.AddIndex(
            model_name='spatiallayer',
            index=models.Index(fields=['publish_to_geoserver'], name='nbms_app_sp_publish_d2eb28_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammeartefactref',
            index=models.Index(fields=['run', 'created_at'], name='nbms_app_mo_run_id_c76606_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammeartefactref',
            index=models.Index(fields=['step', 'created_at'], name='nbms_app_mo_step_id_62b733_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammeartefactref',
            index=models.Index(fields=['label'], name='nbms_app_mo_label_824326_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammeqaresult',
            index=models.Index(fields=['run', 'status'], name='nbms_app_mo_run_id_0fc1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammeqaresult',
            index=models.Index(fields=['step', 'status'], name='nbms_app_mo_step_id_5cd01d_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprogrammeqaresult',
            index=models.Index(fields=['code'], name='nbms_app_mo_code_eff9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialsource',
            index=models.Index(fields=['enabled_by_default', 'is_active'], name='nbms_app_sp_enabled_e0c29e_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialsource',
            index=models.Index(fields=['layer_code'], name='nbms_app_sp_layer_c_3183a1_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialsource',
            index=models.Index(fields=['publish_to_geoserver'], name='nbms_app_sp_publish_07aff3_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialsource',
            index=models.Index(fields=['sensitivity'], name='nbms_app_sp_sensiti_715620_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialsource',
            index=models.Index(fields=['theme'], name='nbms_app_sp_theme_f8efba_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorinputrequirement',
            index=models.Index(fields=['cadence'], name='nbms_app_in_cadence_3601b4_idx'),
        ),
    ]
