# Generated by Django 5.2.9 on 2026-02-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0036_spatiallayer_geoserver_layer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatordatapoint',
            name='programme_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_data_points', to='nbms_app.monitoringprogrammerun'),
        ),
        migrations.AddField(
            model_name='spatialsource',
            name='country_iso3',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddIndex(
            model_name='indicatordatapoint',
            index=models.Index(fields=['programme_run'], name='nbms_app_in_program_49b2de_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialsource',
            index=models.Index(fields=['country_iso3'], name='nbms_app_sp_country_eb2cce_idx'),
        ),
    ]
