# Generated by Django 5.2.9 on 2026-02-08 20:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nbms_app', '0038_alientaxonprofile_ecosystemtype_iucngetnode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemGoldSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('snapshot_date', models.DateField()),
                ('dimension', models.CharField(choices=[('province', 'Province'), ('biome', 'Biome'), ('bioregion', 'Bioregion'), ('threat_category', 'Threat category')], default='biome', max_length=30)),
                ('dimension_key', models.CharField(max_length=120)),
                ('dimension_label', models.CharField(blank=True, max_length=255)),
                ('ecosystem_count', models.PositiveIntegerField(default=0)),
                ('threatened_count', models.PositiveIntegerField(default=0)),
                ('total_area_km2', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('protected_area_km2', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('protected_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='public', max_length=20)),
                ('source_system', models.CharField(blank=True, max_length=100)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecosystem_gold_summaries', to='nbms_app.organisation')),
            ],
            options={
                'ordering': ['-snapshot_date', 'dimension', 'dimension_key'],
                'indexes': [models.Index(fields=['snapshot_date', 'dimension'], name='nbms_app_ec_snapsho_776147_idx'), models.Index(fields=['dimension_key'], name='nbms_app_ec_dimensi_c3f590_idx'), models.Index(fields=['organisation'], name='nbms_app_ec_organis_98910f_idx'), models.Index(fields=['status'], name='nbms_app_ec_status_2689e5_idx'), models.Index(fields=['sensitivity'], name='nbms_app_ec_sensiti_7df001_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot_date', 'dimension', 'dimension_key', 'organisation'), name='uq_ecosystem_gold_summary_dims')],
            },
        ),
        migrations.CreateModel(
            name='IASGoldSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('snapshot_date', models.DateField()),
                ('dimension', models.CharField(choices=[('habitat', 'Habitat'), ('system', 'System'), ('province', 'Province')], default='habitat', max_length=20)),
                ('dimension_key', models.CharField(max_length=120)),
                ('dimension_label', models.CharField(blank=True, max_length=255)),
                ('eicat_category', models.CharField(choices=[('MC', 'Minimal Concern'), ('MN', 'Minor'), ('MO', 'Moderate'), ('MR', 'Major'), ('MV', 'Massive'), ('DD', 'Data Deficient'), ('NE', 'Not Evaluated'), ('NA', 'Not Alien')], default='NE', max_length=3)),
                ('seicat_category', models.CharField(choices=[('MC', 'Minimal Concern'), ('MN', 'Minor'), ('MO', 'Moderate'), ('MR', 'Major'), ('MV', 'Massive'), ('DD', 'Data Deficient'), ('NE', 'Not Evaluated')], default='NE', max_length=3)),
                ('profile_count', models.PositiveIntegerField(default=0)),
                ('invasive_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='public', max_length=20)),
                ('source_system', models.CharField(blank=True, max_length=100)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ias_gold_summaries', to='nbms_app.organisation')),
            ],
            options={
                'ordering': ['-snapshot_date', 'dimension', 'dimension_key', 'eicat_category', 'seicat_category'],
                'indexes': [models.Index(fields=['snapshot_date', 'dimension'], name='nbms_app_ia_snapsho_115d72_idx'), models.Index(fields=['dimension_key'], name='nbms_app_ia_dimensi_916c58_idx'), models.Index(fields=['eicat_category', 'seicat_category'], name='nbms_app_ia_eicat_c_682c65_idx'), models.Index(fields=['organisation'], name='nbms_app_ia_organis_4dddfa_idx'), models.Index(fields=['status'], name='nbms_app_ia_status_085e8c_idx'), models.Index(fields=['sensitivity'], name='nbms_app_ia_sensiti_e7bfa1_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot_date', 'dimension', 'dimension_key', 'eicat_category', 'seicat_category', 'organisation'), name='uq_ias_gold_summary_dims')],
            },
        ),
        migrations.CreateModel(
            name='IndicatorRegistryCoverageRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('require_ecosystem_registry', models.BooleanField(default=False)),
                ('require_taxon_registry', models.BooleanField(default=False)),
                ('require_ias_registry', models.BooleanField(default=False)),
                ('min_ecosystem_count', models.PositiveIntegerField(default=1)),
                ('min_taxon_count', models.PositiveIntegerField(default=1)),
                ('min_ias_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registry_coverage_requirement', to='nbms_app.indicator')),
            ],
            options={
                'indexes': [models.Index(fields=['require_ecosystem_registry', 'require_taxon_registry', 'require_ias_registry'], name='nbms_app_in_require_7ec954_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistryEvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_uuid', models.UUIDField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='internal', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_evidence_links', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registry_evidence_links', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_object_links', to='nbms_app.evidence')),
            ],
            options={
                'ordering': ['content_type', 'object_uuid', 'evidence__title', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_uuid'], name='nbms_app_re_content_59c75a_idx'), models.Index(fields=['evidence'], name='nbms_app_re_evidenc_082d6e_idx'), models.Index(fields=['status'], name='nbms_app_re_status_5e93d6_idx'), models.Index(fields=['sensitivity'], name='nbms_app_re_sensiti_1e0128_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_uuid', 'evidence'), name='uq_registry_evidence_link')],
            },
        ),
        migrations.CreateModel(
            name='TaxonGoldSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('snapshot_date', models.DateField()),
                ('taxon_rank', models.CharField(blank=True, max_length=80)),
                ('is_native', models.BooleanField(blank=True, null=True)),
                ('is_endemic', models.BooleanField(default=False)),
                ('has_voucher', models.BooleanField(default=False)),
                ('is_ias', models.BooleanField(default=False)),
                ('taxon_count', models.PositiveIntegerField(default=0)),
                ('voucher_count', models.PositiveIntegerField(default=0)),
                ('ias_profile_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='public', max_length=20)),
                ('source_system', models.CharField(blank=True, max_length=100)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxon_gold_summaries', to='nbms_app.organisation')),
            ],
            options={
                'ordering': ['-snapshot_date', 'taxon_rank', 'organisation_id'],
                'indexes': [models.Index(fields=['snapshot_date', 'taxon_rank'], name='nbms_app_ta_snapsho_b997f2_idx'), models.Index(fields=['is_native', 'is_endemic'], name='nbms_app_ta_is_nati_f220e1_idx'), models.Index(fields=['has_voucher', 'is_ias'], name='nbms_app_ta_has_vou_8b6b55_idx'), models.Index(fields=['organisation'], name='nbms_app_ta_organis_9d6b4c_idx'), models.Index(fields=['status'], name='nbms_app_ta_status_40d08a_idx'), models.Index(fields=['sensitivity'], name='nbms_app_ta_sensiti_910df0_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot_date', 'taxon_rank', 'is_native', 'is_endemic', 'has_voucher', 'is_ias', 'organisation'), name='uq_taxon_gold_summary_dims')],
            },
        ),
    ]
