# Generated by Django 5.2.9 on 2026-02-09 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0039_ecosystemgoldsummary_iasgoldsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingcycle',
            name='allowed_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reportingcycle',
            name='default_language',
            field=models.CharField(blank=True, default='English', max_length=32),
        ),
        migrations.AddField(
            model_name='reportingcycle',
            name='submission_window_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportingcycle',
            name='submission_window_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='country_name',
            field=models.CharField(default='South Africa', max_length=255),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reporting_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='final_content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='focal_point_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focal_point_reporting_instances', to='nbms_app.organisation'),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='publishing_authority_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishing_authority_reporting_instances', to='nbms_app.organisation'),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='report_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_reporting_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplatepackresponse',
            name='current_content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reporttemplatepackresponse',
            name='current_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reporttemplatepackresponse',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplatepackresponse',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_template_pack_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplatepackresponse',
            name='locked_for_editing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportinginstance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('section_review', 'Section review'), ('technical_review', 'Technical review'), ('secretariat_consolidation', 'Secretariat consolidation'), ('publishing_authority_review', 'Publishing authority review'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('submitted', 'Submitted'), ('released', 'Released'), ('archived', 'Archived')], default='draft', max_length=40),
        ),
        migrations.CreateModel(
            name='ReportCommentThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('json_path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_comment_threads', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_report_comment_threads', to=settings.AUTH_USER_MODEL)),
                ('section_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_threads', to='nbms_app.reporttemplatepackresponse')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_comments', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nbms_app.reportcommentthread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportSectionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('content_snapshot', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('parent_hash', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_section_revisions', to=settings.AUTH_USER_MODEL)),
                ('section_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='nbms_app.reporttemplatepackresponse')),
            ],
            options={
                'ordering': ['section_response_id', '-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportSuggestedChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('base_version', models.PositiveIntegerField()),
                ('patch_json', models.JSONField(blank=True, default=dict)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_suggested_changes', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_report_suggested_changes', to=settings.AUTH_USER_MODEL)),
                ('section_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_changes', to='nbms_app.reporttemplatepackresponse')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportWorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('submit', 'Submit'), ('review', 'Review'), ('approve', 'Approve'), ('reject', 'Reject'), ('technical_approve', 'Technical approve'), ('consolidate', 'Consolidate'), ('publishing_approve', 'Publishing authority approve'), ('finalize', 'Finalize'), ('unlock', 'Unlock')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_workflow_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportExportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('json', 'JSON'), ('dossier', 'Dossier ZIP')], max_length=20)),
                ('storage_path', models.CharField(max_length=512)),
                ('content_hash', models.CharField(max_length=64)),
                ('immutable', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_report_export_artifacts', to=settings.AUTH_USER_MODEL)),
                ('reporting_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_export_artifacts', to='nbms_app.reportinginstance')),
                ('linked_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_artifacts', to='nbms_app.reportworkflowaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportDossierArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('storage_path', models.CharField(max_length=512)),
                ('content_hash', models.CharField(max_length=64)),
                ('manifest_json', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_report_dossiers', to=settings.AUTH_USER_MODEL)),
                ('reporting_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_artifacts', to='nbms_app.reportinginstance')),
                ('linked_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_artifacts', to='nbms_app.reportworkflowaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportWorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_type', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('steps_json', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['object_type', 'is_active'], name='nbms_app_re_object__d95502_idx')],
                'constraints': [models.UniqueConstraint(fields=('object_type', 'name'), name='uq_report_workflow_definition')],
            },
        ),
        migrations.CreateModel(
            name='ReportWorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('latest_content_hash', models.CharField(blank=True, max_length=64)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='nbms_app.reportworkflowdefinition')),
                ('reporting_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='nbms_app.reportinginstance')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='reportworkflowaction',
            name='workflow_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='nbms_app.reportworkflowinstance'),
        ),
        migrations.CreateModel(
            name='ReportWorkflowSectionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_report_sections', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvals', to='nbms_app.reporttemplatepacksection')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_approvals', to='nbms_app.reportworkflowinstance')),
            ],
            options={
                'ordering': ['section__ordering', 'section__code'],
            },
        ),
        migrations.CreateModel(
            name='AnnexSectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('decision_topic_code', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('reporting_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annex_responses', to='nbms_app.reportinginstance')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annex_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordering', 'decision_topic_code'],
                'indexes': [models.Index(fields=['reporting_instance', 'is_enabled'], name='nbms_app_an_reporti_3409e8_idx'), models.Index(fields=['ordering', 'decision_topic_code'], name='nbms_app_an_orderin_b61e2d_idx')],
                'constraints': [models.UniqueConstraint(fields=('reporting_instance', 'decision_topic_code'), name='uq_annex_response_topic')],
            },
        ),
        migrations.AddIndex(
            model_name='reportcommentthread',
            index=models.Index(fields=['section_response', 'status'], name='nbms_app_re_section_2394ee_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcommentthread',
            index=models.Index(fields=['json_path'], name='nbms_app_re_json_pa_bf5c27_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcomment',
            index=models.Index(fields=['thread', 'created_at'], name='nbms_app_re_thread__ed437b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsectionrevision',
            index=models.Index(fields=['section_response', 'version'], name='nbms_app_re_section_13fdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsectionrevision',
            index=models.Index(fields=['content_hash'], name='nbms_app_re_content_74374d_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportsectionrevision',
            constraint=models.UniqueConstraint(fields=('section_response', 'version'), name='uq_report_section_revision_version'),
        ),
        migrations.AddConstraint(
            model_name='reportsectionrevision',
            constraint=models.UniqueConstraint(fields=('section_response', 'content_hash'), name='uq_report_section_revision_hash'),
        ),
        migrations.AddIndex(
            model_name='reportsuggestedchange',
            index=models.Index(fields=['section_response', 'status'], name='nbms_app_re_section_b00386_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsuggestedchange',
            index=models.Index(fields=['base_version'], name='nbms_app_re_base_ve_65fd10_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportartifact',
            index=models.Index(fields=['reporting_instance', 'format', 'created_at'], name='nbms_app_re_reporti_fc4cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportartifact',
            index=models.Index(fields=['content_hash'], name='nbms_app_re_content_deee33_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdossierartifact',
            index=models.Index(fields=['reporting_instance', 'created_at'], name='nbms_app_re_reporti_2bc54c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdossierartifact',
            index=models.Index(fields=['content_hash'], name='nbms_app_re_content_981158_idx'),
        ),
        migrations.AddIndex(
            model_name='reportworkflowinstance',
            index=models.Index(fields=['reporting_instance', 'status'], name='nbms_app_re_reporti_c129d5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportworkflowinstance',
            index=models.Index(fields=['current_step'], name='nbms_app_re_current_9654d8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportworkflowaction',
            index=models.Index(fields=['workflow_instance', 'created_at'], name='nbms_app_re_workflo_dc8d64_idx'),
        ),
        migrations.AddIndex(
            model_name='reportworkflowaction',
            index=models.Index(fields=['action_type', 'created_at'], name='nbms_app_re_action__6f3179_idx'),
        ),
        migrations.AddIndex(
            model_name='reportworkflowsectionapproval',
            index=models.Index(fields=['workflow_instance', 'approved'], name='nbms_app_re_workflo_cb243f_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportworkflowsectionapproval',
            constraint=models.UniqueConstraint(fields=('workflow_instance', 'section'), name='uq_report_workflow_section_approval'),
        ),
    ]
