# Generated by Django 5.2.9 on 2026-02-09 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0040_reportingcycle_allowed_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('context_hash', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportNarrativeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('section_code', models.CharField(max_length=100)),
                ('block_key', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('storage_path', models.CharField(blank=True, max_length=512)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('current_content_hash', models.CharField(blank=True, max_length=64)),
                ('html_snapshot', models.TextField(blank=True)),
                ('text_snapshot', models.TextField(blank=True)),
                ('onlyoffice_document_key', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['reporting_instance_id', 'section_code', 'block_key'],
            },
        ),
        migrations.CreateModel(
            name='ReportNarrativeBlockVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('storage_path', models.CharField(max_length=512)),
                ('content_hash', models.CharField(max_length=64)),
                ('html_snapshot', models.TextField(blank=True)),
                ('text_snapshot', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['block_id', '-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportSignoffRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signer_role', models.CharField(blank=True, max_length=80)),
                ('body', models.CharField(blank=True, max_length=120)),
                ('state_from', models.CharField(blank=True, max_length=40)),
                ('state_to', models.CharField(blank=True, max_length=40)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('snapshot_hash_pointer', models.CharField(blank=True, max_length=64)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-signed_at', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='reportcommentthread',
            name='field_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='reportcommentthread',
            name='object_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='report_family',
            field=models.CharField(choices=[('CBD_NATIONAL_REPORT', 'CBD National Report')], default='CBD_NATIONAL_REPORT', max_length=64),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='report_label',
            field=models.CharField(choices=[('NR7', 'NR7'), ('NR8', 'NR8')], default='NR7', max_length=20),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='reporting_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportinginstance',
            name='reporting_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='context_filters_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='context_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='export_docx_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='export_docx_storage_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='export_json_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='export_json_storage_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='export_pdf_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='export_pdf_storage_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='report_family',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='report_label',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='reporting_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='reporting_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportingsnapshot',
            name='resolved_values_manifest_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reportsuggestedchange',
            name='diff_patch',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportsuggestedchange',
            name='field_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='reportsuggestedchange',
            name='object_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsuggestedchange',
            name='old_value_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reportsuggestedchange',
            name='proposed_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reportcommentthread',
            name='json_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reportcommentthread',
            name='section_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_threads', to='nbms_app.reporttemplatepackresponse'),
        ),
        migrations.AlterField(
            model_name='reportinginstance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('internal_review', 'Internal review'), ('technical_committee_review', 'Technical Committee review'), ('technical_committee_approved', 'Technical Committee approved'), ('dffe_clearance', 'DFFE clearance'), ('final_signed_off', 'Final signed off'), ('frozen', 'Frozen'), ('public_released', 'Public released'), ('section_review', 'Section review'), ('technical_review', 'Technical review'), ('secretariat_consolidation', 'Secretariat consolidation'), ('publishing_authority_review', 'Publishing authority review'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('submitted', 'Submitted'), ('released', 'Released'), ('archived', 'Archived')], default='draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='reportsuggestedchange',
            name='base_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportsuggestedchange',
            name='section_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_changes', to='nbms_app.reporttemplatepackresponse'),
        ),
        migrations.AlterField(
            model_name='reportsuggestedchange',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportworkflowaction',
            name='action_type',
            field=models.CharField(choices=[('start_progress', 'Start progress'), ('request_internal_review', 'Request internal review'), ('request_technical_committee_review', 'Request Technical Committee review'), ('technical_committee_approve', 'Technical Committee approve'), ('dffe_clearance_approve', 'DFFE clearance approve'), ('final_signoff', 'Final sign-off'), ('freeze', 'Freeze'), ('public_release', 'Public release'), ('section_complete', 'Section complete'), ('submit', 'Submit'), ('review', 'Review'), ('approve', 'Approve'), ('reject', 'Reject'), ('technical_approve', 'Technical approve'), ('consolidate', 'Consolidate'), ('publishing_approve', 'Publishing authority approve'), ('finalize', 'Finalize'), ('unlock', 'Unlock')], max_length=64),
        ),
        migrations.AddIndex(
            model_name='reportcommentthread',
            index=models.Index(fields=['object_uuid', 'field_name', 'status'], name='nbms_app_re_object__2bcee6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsuggestedchange',
            index=models.Index(fields=['object_uuid', 'field_name', 'status'], name='nbms_app_re_object__0218e4_idx'),
        ),
        migrations.AddField(
            model_name='reportcontext',
            name='reporting_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='nbms_app.reportinginstance'),
        ),
        migrations.AddField(
            model_name='reportcontext',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_report_contexts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcontext',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_contexts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportnarrativeblock',
            name='reporting_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_blocks', to='nbms_app.reportinginstance'),
        ),
        migrations.AddField(
            model_name='reportnarrativeblock',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_narrative_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportnarrativeblockversion',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='nbms_app.reportnarrativeblock'),
        ),
        migrations.AddField(
            model_name='reportnarrativeblockversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_narrative_block_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportsignoffrecord',
            name='reporting_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoff_records', to='nbms_app.reportinginstance'),
        ),
        migrations.AddField(
            model_name='reportsignoffrecord',
            name='signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_signoff_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportsignoffrecord',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signoff_records', to='nbms_app.reportingsnapshot'),
        ),
        migrations.AddIndex(
            model_name='reportcontext',
            index=models.Index(fields=['reporting_instance', 'user', 'is_active'], name='nbms_app_re_reporti_7f9e34_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcontext',
            index=models.Index(fields=['reporting_instance', 'session_key'], name='nbms_app_re_reporti_290ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcontext',
            index=models.Index(fields=['context_hash'], name='nbms_app_re_context_af9b92_idx'),
        ),
        migrations.AddIndex(
            model_name='reportnarrativeblock',
            index=models.Index(fields=['reporting_instance', 'section_code'], name='nbms_app_re_reporti_3943fc_idx'),
        ),
        migrations.AddIndex(
            model_name='reportnarrativeblock',
            index=models.Index(fields=['onlyoffice_document_key'], name='nbms_app_re_onlyoff_dcc84a_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportnarrativeblock',
            constraint=models.UniqueConstraint(fields=('reporting_instance', 'section_code', 'block_key'), name='uq_reporting_narrative_block'),
        ),
        migrations.AddIndex(
            model_name='reportnarrativeblockversion',
            index=models.Index(fields=['block', 'version'], name='nbms_app_re_block_i_a293ef_idx'),
        ),
        migrations.AddIndex(
            model_name='reportnarrativeblockversion',
            index=models.Index(fields=['content_hash'], name='nbms_app_re_content_d07354_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportnarrativeblockversion',
            constraint=models.UniqueConstraint(fields=('block', 'version'), name='uq_reporting_narrative_block_version'),
        ),
        migrations.AddConstraint(
            model_name='reportnarrativeblockversion',
            constraint=models.UniqueConstraint(fields=('block', 'content_hash'), name='uq_reporting_narrative_block_hash'),
        ),
        migrations.AddIndex(
            model_name='reportsignoffrecord',
            index=models.Index(fields=['reporting_instance', 'signed_at'], name='nbms_app_re_reporti_905e01_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsignoffrecord',
            index=models.Index(fields=['state_to', 'signed_at'], name='nbms_app_re_state_t_56dc85_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsignoffrecord',
            index=models.Index(fields=['body'], name='nbms_app_re_body_91f91b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsignoffrecord',
            index=models.Index(fields=['snapshot_hash_pointer'], name='nbms_app_re_snapsho_5846f3_idx'),
        ),
    ]
