# Generated by Django 5.2.9 on 2026-02-25 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0041_reportcontext_reportnarrativeblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatordataseries',
            name='sense_check_attested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicatordataseries',
            name='sense_check_attested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatordataseries',
            name='sense_check_attested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attested_indicator_data_series', to=settings.AUTH_USER_MODEL),
        ),
    ]
