# Generated by Django 5.2.9 on 2026-02-25 18:18

import django.db.models.deletion
import nbms_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0042_indicatordataseries_sense_check_attested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme_id', models.CharField(choices=[('fynbos', 'Fynbos'), ('gbif_clean', 'GBIF Clean'), ('high_contrast', 'High contrast'), ('dark_pro', 'Dark Pro')], default='fynbos', max_length=32)),
                ('density', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=20)),
                ('default_geography', models.CharField(choices=[('national', 'National'), ('province', 'Province'), ('district', 'District'), ('municipality', 'Municipality')], default='national', max_length=20)),
                ('default_geography_code', models.CharField(blank=True, default='', max_length=64)),
                ('saved_filters', models.JSONField(blank=True, default=nbms_app.models.default_preference_saved_filters)),
                ('watchlist', models.JSONField(blank=True, default=nbms_app.models.default_preference_watchlist)),
                ('dashboard_layout', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['theme_id'], name='nbms_app_us_theme_i_d575ae_idx'), models.Index(fields=['updated_at'], name='nbms_app_us_updated_df328e_idx')],
            },
        ),
    ]
