# Generated by Django 5.2.9 on 2026-02-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0043_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=16),
        ),
    ]
