# Generated by Django 5.2.9 on 2026-02-25 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0044_userpreference_theme_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('record_type', models.CharField(choices=[('indicator_series', 'Indicator series'), ('spatial_layer', 'Spatial layer'), ('report_export', 'Report export'), ('registry_export', 'Registry export'), ('custom_bundle', 'Custom bundle')], max_length=40)),
                ('object_type', models.CharField(blank=True, default='', max_length=80)),
                ('object_uuid', models.UUIDField(blank=True, null=True)),
                ('query_snapshot', models.JSONField(blank=True, default=dict)),
                ('contributing_sources', models.JSONField(blank=True, default=list)),
                ('access_level_at_time', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted')], default='internal', max_length=20)),
                ('citation_text', models.TextField(blank=True)),
                ('citation_id', models.CharField(blank=True, max_length=80)),
                ('file_asset_path', models.CharField(blank=True, max_length=512)),
                ('file_asset_name', models.CharField(blank=True, max_length=255)),
                ('file_content_type', models.CharField(blank=True, max_length=120)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('regen_params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_by', 'created_at'], name='nbms_app_do_created_498fe8_idx'), models.Index(fields=['record_type', 'created_at'], name='nbms_app_do_record__c66323_idx'), models.Index(fields=['object_type', 'object_uuid'], name='nbms_app_do_object__896991_idx'), models.Index(fields=['status', 'created_at'], name='nbms_app_do_status_a0880b_idx'), models.Index(fields=['access_level_at_time'], name='nbms_app_do_access__8bd1de_idx')],
            },
        ),
    ]
