# Generated by Django 5.2.9 on 2026-02-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0045_downloadrecord'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['last_updated_on'], name='nbms_app_in_last_up_3dd784_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['update_frequency'], name='nbms_app_in_update__1a0d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['coverage_time_start_year'], name='nbms_app_in_coverag_803fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['coverage_time_end_year'], name='nbms_app_in_coverag_b22739_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['status', 'sensitivity', 'last_updated_on'], name='nbms_app_in_status_f5791a_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorframeworkindicatorlink',
            index=models.Index(fields=['indicator', 'is_active'], name='nbms_app_in_indicat_6b71bc_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorframeworkindicatorlink',
            index=models.Index(fields=['framework_indicator', 'is_active'], name='nbms_app_in_framewo_05a1f4_idx'),
        ),
    ]
