# Generated by Django 5.2.11 on 2026-03-03 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbms_app', '0046_indicator_nbms_app_in_last_up_3dd784_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernedNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity_type', models.CharField(choices=[('dashboard', 'Dashboard'), ('framework', 'Framework'), ('target', 'Target'), ('indicator', 'Indicator')], max_length=30)),
                ('entity_key', models.CharField(max_length=160)),
                ('entity_label', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(default='Narrative', max_length=255)),
                ('sections_json', models.JSONField(blank=True, default=list)),
                ('markdown_snapshot', models.TextField(blank=True)),
                ('html_snapshot', models.TextField(blank=True)),
                ('summary_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('qa_status', models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('validated', 'Validated'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('iplc_sensitive', 'IPLC-sensitive')], default='internal', max_length=20)),
                ('provenance_url', models.URLField(blank=True)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_governed_narratives', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_governed_narratives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entity_type', 'entity_key'],
            },
        ),
        migrations.CreateModel(
            name='GovernedNarrativeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('sections_json', models.JSONField(blank=True, default=list)),
                ('markdown_snapshot', models.TextField(blank=True)),
                ('html_snapshot', models.TextField(blank=True)),
                ('summary_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('qa_status', models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('validated', 'Validated'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('provenance_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_governed_narrative_versions', to=settings.AUTH_USER_MODEL)),
                ('narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='nbms_app.governednarrative')),
            ],
            options={
                'ordering': ['narrative_id', '-version', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='governednarrative',
            index=models.Index(fields=['entity_type', 'entity_key'], name='nbms_app_go_entity__6f93ea_idx'),
        ),
        migrations.AddIndex(
            model_name='governednarrative',
            index=models.Index(fields=['status', 'updated_at'], name='nbms_app_go_status_b1def7_idx'),
        ),
        migrations.AddIndex(
            model_name='governednarrative',
            index=models.Index(fields=['sensitivity'], name='nbms_app_go_sensiti_311078_idx'),
        ),
        migrations.AddConstraint(
            model_name='governednarrative',
            constraint=models.UniqueConstraint(fields=('entity_type', 'entity_key'), name='uq_governed_narrative_entity'),
        ),
        migrations.AddIndex(
            model_name='governednarrativeversion',
            index=models.Index(fields=['narrative', 'version'], name='nbms_app_go_narrati_960a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='governednarrativeversion',
            index=models.Index(fields=['status', 'created_at'], name='nbms_app_go_status_70b4ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='governednarrativeversion',
            constraint=models.UniqueConstraint(fields=('narrative', 'version'), name='uq_governed_narrative_version'),
        ),
    ]
