from django.urls import path

from nbms_app import api_spa
from nbms_app import api_spatial


urlpatterns = [
    path("auth/me", api_spa.api_auth_me, name="api_auth_me"),
    path("auth/capabilities", api_spa.api_auth_capabilities, name="api_auth_capabilities"),
    path("auth/csrf", api_spa.api_auth_csrf, name="api_auth_csrf"),
    path("help/sections", api_spa.api_help_sections, name="api_help_sections"),
    path("system/health", api_spa.api_system_health, name="api_system_health"),
    path("dashboard/summary", api_spa.api_dashboard_summary, name="api_dashboard_summary"),
    path("programmes", api_spa.api_programme_list, name="api_programme_list"),
    path(
        "programmes/<uuid:programme_uuid>",
        api_spa.api_programme_detail,
        name="api_programme_detail",
    ),
    path(
        "programmes/<uuid:programme_uuid>/runs",
        api_spa.api_programme_run_create,
        name="api_programme_run_create",
    ),
    path(
        "programmes/runs/<uuid:run_uuid>",
        api_spa.api_programme_run_detail,
        name="api_programme_run_detail",
    ),
    path(
        "programmes/runs/<uuid:run_uuid>/report",
        api_spa.api_programme_run_report,
        name="api_programme_run_report",
    ),
    path(
        "integrations/birdie/dashboard",
        api_spa.api_birdie_dashboard,
        name="api_birdie_dashboard",
    ),
    path("reporting/instances", api_spa.api_reporting_instances, name="api_reporting_instances"),
    path(
        "reporting/instances/<uuid:instance_uuid>/nr7/summary",
        api_spa.api_reporting_nr7_summary,
        name="api_reporting_nr7_summary",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/nr7/export.pdf",
        api_spa.api_reporting_nr7_pdf,
        name="api_reporting_nr7_pdf",
    ),
    path(
        "reports/<uuid:instance_uuid>/workspace",
        api_spa.api_reporting_workspace_summary,
        name="api_reporting_workspace_summary",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/<str:section_code>",
        api_spa.api_reporting_workspace_section,
        name="api_reporting_workspace_section",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/<str:section_code>/history",
        api_spa.api_reporting_workspace_section_history,
        name="api_reporting_workspace_section_history",
    ),
    path(
        "reports/<uuid:instance_uuid>/context",
        api_spa.api_reporting_workspace_context,
        name="api_reporting_workspace_context",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/<str:section_code>/preview",
        api_spa.api_reporting_workspace_section_preview,
        name="api_reporting_workspace_section_preview",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/<str:section_code>/charts",
        api_spa.api_reporting_workspace_section_charts,
        name="api_reporting_workspace_section_charts",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/<str:section_code>/narrative/render",
        api_spa.api_reporting_workspace_section_narrative_render,
        name="api_reporting_workspace_section_narrative_render",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/<str:section_code>/narrative/blocks",
        api_spa.api_reporting_workspace_section_narrative_blocks,
        name="api_reporting_workspace_section_narrative_blocks",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/<str:section_code>/narrative/blocks/<str:block_key>/editor-config",
        api_spa.api_reporting_workspace_section_narrative_editor_config,
        name="api_reporting_workspace_section_narrative_editor_config",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/<str:section_code>/narrative/blocks/<str:block_key>/document",
        api_spa.api_reporting_workspace_section_narrative_block_document,
        name="api_reporting_workspace_section_narrative_block_document",
    ),
    path(
        "reports/narrative/callback/<uuid:block_uuid>",
        api_spa.api_reporting_workspace_onlyoffice_callback,
        name="api_reporting_workspace_onlyoffice_callback",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/section-iii/generate-skeleton",
        api_spa.api_reporting_workspace_generate_section_iii,
        name="api_reporting_workspace_generate_section_iii",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/section-iv/recompute-rollup",
        api_spa.api_reporting_workspace_recompute_section_iv,
        name="api_reporting_workspace_recompute_section_iv",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/<str:section_code>/comments",
        api_spa.api_reporting_workspace_section_comments,
        name="api_reporting_workspace_section_comments",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/<str:section_code>/comments/<uuid:thread_uuid>/status",
        api_spa.api_reporting_workspace_comment_thread_status,
        name="api_reporting_workspace_comment_thread_status",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/<str:section_code>/suggestions",
        api_spa.api_reporting_workspace_section_suggestions,
        name="api_reporting_workspace_section_suggestions",
    ),
    path(
        "reports/<uuid:instance_uuid>/sections/<str:section_code>/suggestions/<uuid:suggestion_uuid>/decision",
        api_spa.api_reporting_workspace_suggestion_decide,
        name="api_reporting_workspace_suggestion_decide",
    ),
    path(
        "reports/<uuid:instance_uuid>/workflow",
        api_spa.api_reporting_workspace_workflow,
        name="api_reporting_workspace_workflow",
    ),
    path(
        "reports/<uuid:instance_uuid>/workflow/action",
        api_spa.api_reporting_workspace_workflow_action,
        name="api_reporting_workspace_workflow_action",
    ),
    path(
        "reports/<uuid:instance_uuid>/export.pdf",
        api_spa.api_reporting_workspace_export_pdf,
        name="api_reporting_workspace_export_pdf",
    ),
    path(
        "reports/<uuid:instance_uuid>/export.docx",
        api_spa.api_reporting_workspace_export_docx,
        name="api_reporting_workspace_export_docx",
    ),
    path(
        "reports/<uuid:instance_uuid>/export",
        api_spa.api_reporting_workspace_export_json,
        name="api_reporting_workspace_export_json",
    ),
    path(
        "reports/<uuid:instance_uuid>/dossier",
        api_spa.api_reporting_workspace_generate_dossier,
        name="api_reporting_workspace_generate_dossier",
    ),
    path(
        "reports/<uuid:instance_uuid>/dossier/latest",
        api_spa.api_reporting_workspace_latest_dossier,
        name="api_reporting_workspace_latest_dossier",
    ),
    path(
        "reports/<uuid:instance_uuid>/ort-validation",
        api_spa.api_reporting_workspace_ort_validation,
        name="api_reporting_workspace_ort_validation",
    ),
    path(
        "reports/<uuid:instance_uuid>/carry-forward/nr8",
        api_spa.api_reporting_workspace_create_nr8_from_nr7,
        name="api_reporting_workspace_create_nr8_from_nr7",
    ),
    path(
        "reports/<uuid:instance_uuid>/diff",
        api_spa.api_reporting_workspace_diff,
        name="api_reporting_workspace_diff",
    ),
    path(
        "reports/<uuid:instance_uuid>/public",
        api_spa.api_reporting_public_view,
        name="api_reporting_public_view",
    ),
    path("indicators", api_spa.api_indicator_list, name="api_indicator_list"),
    path("indicators/<uuid:indicator_uuid>", api_spa.api_indicator_detail, name="api_indicator_detail"),
    path(
        "indicators/<uuid:indicator_uuid>/datasets",
        api_spa.api_indicator_datasets,
        name="api_indicator_datasets",
    ),
    path(
        "indicators/<uuid:indicator_uuid>/series",
        api_spa.api_indicator_series_summary,
        name="api_indicator_series_summary",
    ),
    path(
        "indicators/<uuid:indicator_uuid>/map",
        api_spa.api_indicator_map,
        name="api_indicator_map",
    ),
    path(
        "indicators/<uuid:indicator_uuid>/validation",
        api_spa.api_indicator_validation,
        name="api_indicator_validation",
    ),
    path(
        "indicators/<uuid:indicator_uuid>/methods",
        api_spa.api_indicator_methods,
        name="api_indicator_methods",
    ),
    path(
        "indicators/<uuid:indicator_uuid>/methods/<uuid:profile_uuid>/run",
        api_spa.api_indicator_method_run,
        name="api_indicator_method_run",
    ),
    path(
        "indicators/<uuid:indicator_uuid>/transition",
        api_spa.api_indicator_transition,
        name="api_indicator_transition",
    ),
    path("spatial/layers", api_spatial.api_spatial_layers, name="api_spatial_layers"),
    path("spatial/layers/upload", api_spatial.api_spatial_upload_layer, name="api_spatial_upload_layer"),
    path(
        "spatial/layers/<slug:slug>/features",
        api_spatial.api_spatial_layer_features,
        name="api_spatial_layer_features",
    ),
    path(
        "spatial/layers/<str:layer_code>/export.geojson",
        api_spatial.api_spatial_layer_export_geojson,
        name="api_spatial_layer_export_geojson",
    ),
    path("ogc", api_spatial.api_ogc_landing, name="api_ogc_landing"),
    path("ogc/collections", api_spatial.api_ogc_collections, name="api_ogc_collections"),
    path(
        "ogc/collections/<str:layer_code>/items",
        api_spatial.api_ogc_collection_items,
        name="api_ogc_collection_items",
    ),
    path("tiles/<str:layer_code>/tilejson", api_spatial.api_tiles_tilejson, name="api_tiles_tilejson"),
    path("tiles/<str:layer_code>/<int:z>/<int:x>/<int:y>.pbf", api_spatial.api_tiles_mvt, name="api_tiles_mvt"),
    path("template-packs", api_spa.api_template_pack_list, name="api_template_pack_list"),
    path(
        "template-packs/<str:pack_code>/sections",
        api_spa.api_template_pack_sections,
        name="api_template_pack_sections",
    ),
    path(
        "template-packs/<str:pack_code>/instances/<uuid:instance_uuid>/responses",
        api_spa.api_template_pack_instance_responses,
        name="api_template_pack_instance_responses",
    ),
    path(
        "template-packs/<str:pack_code>/instances/<uuid:instance_uuid>/validate",
        api_spa.api_template_pack_validate,
        name="api_template_pack_validate",
    ),
    path(
        "template-packs/<str:pack_code>/instances/<uuid:instance_uuid>/export.pdf",
        api_spa.api_template_pack_pdf,
        name="api_template_pack_pdf",
    ),
    path(
        "template-packs/<str:pack_code>/instances/<uuid:instance_uuid>/export",
        api_spa.api_template_pack_export,
        name="api_template_pack_export",
    ),
    path(
        "report-products",
        api_spa.api_report_product_list,
        name="api_report_product_list",
    ),
    path(
        "report-products/runs",
        api_spa.api_report_product_runs,
        name="api_report_product_runs",
    ),
    path("registries/ecosystems", api_spa.api_registry_ecosystems, name="api_registry_ecosystems"),
    path(
        "registries/ecosystems/<uuid:ecosystem_uuid>",
        api_spa.api_registry_ecosystem_detail,
        name="api_registry_ecosystem_detail",
    ),
    path("registries/taxa", api_spa.api_registry_taxa, name="api_registry_taxa"),
    path(
        "registries/taxa/<uuid:taxon_uuid>",
        api_spa.api_registry_taxon_detail,
        name="api_registry_taxon_detail",
    ),
    path("registries/ias", api_spa.api_registry_ias, name="api_registry_ias"),
    path(
        "registries/ias/<uuid:profile_uuid>",
        api_spa.api_registry_ias_detail,
        name="api_registry_ias_detail",
    ),
    path("registries/gold", api_spa.api_registry_gold_summaries, name="api_registry_gold_summaries"),
    path(
        "registries/<str:object_type>/<uuid:object_uuid>/evidence",
        api_spa.api_registry_object_evidence,
        name="api_registry_object_evidence",
    ),
    path(
        "registries/<str:object_type>/<uuid:object_uuid>/transition",
        api_spa.api_registry_transition,
        name="api_registry_transition",
    ),
    path(
        "programmes/templates",
        api_spa.api_programme_templates,
        name="api_programme_templates",
    ),
    path(
        "report-products/<str:product_code>/preview",
        api_spa.api_report_product_preview,
        name="api_report_product_preview",
    ),
    path(
        "report-products/<str:product_code>/export.html",
        api_spa.api_report_product_html,
        name="api_report_product_html",
    ),
    path(
        "report-products/<str:product_code>/export.pdf",
        api_spa.api_report_product_pdf,
        name="api_report_product_pdf",
    ),
]
