from django.urls import path

from nbms_app import views
from nbms_app import views_alignment_bulk
from nbms_app import views_audit
from nbms_app import views_metrics
from nbms_app import views_notifications

app_name = "nbms_app"

urlpatterns = [
    path("", views.home, name="home"),
    path("health/", views.health_db, name="health_db"),
    path("healthz/", views.healthz, name="healthz"),
    path("readyz/", views.readyz, name="readyz"),
    path("health/storage/", views.health_storage, name="health_storage"),
    path("manage/organisations/", views.manage_organisation_list, name="manage_organisation_list"),
    path("manage/organisations/new/", views.manage_organisation_create, name="manage_organisation_create"),
    path("manage/organisations/<int:org_id>/edit/", views.manage_organisation_edit, name="manage_organisation_edit"),
    path("manage/users/", views.manage_user_list, name="manage_user_list"),
    path("manage/users/new/", views.manage_user_create, name="manage_user_create"),
    path("manage/users/<int:user_id>/edit/", views.manage_user_edit, name="manage_user_edit"),
    path("manage/users/<int:user_id>/send-reset/", views.manage_user_send_reset, name="manage_user_send_reset"),
    path("national-targets/", views.national_target_list, name="national_target_list"),
    path("national-targets/new/", views.national_target_create, name="national_target_create"),
    path("national-targets/<uuid:target_uuid>/", views.national_target_detail, name="national_target_detail"),
    path("national-targets/<uuid:target_uuid>/edit/", views.national_target_edit, name="national_target_edit"),
    path(
        "catalog/national-targets/<uuid:target_uuid>/alignments/",
        views.national_target_alignments,
        name="national_target_alignments",
    ),
    path(
        "catalog/national-targets/alignments/<int:link_id>/archive/",
        views.national_target_alignment_archive,
        name="national_target_alignment_archive",
    ),
    path("indicators/", views.indicator_list, name="indicator_list"),
    path("indicators/new/", views.indicator_create, name="indicator_create"),
    path("indicators/<uuid:indicator_uuid>/", views.indicator_detail, name="indicator_detail"),
    path("indicators/<uuid:indicator_uuid>/edit/", views.indicator_edit, name="indicator_edit"),
    path(
        "catalog/national-indicators/<uuid:indicator_uuid>/alignments/",
        views.indicator_alignments,
        name="indicator_alignments",
    ),
    path(
        "catalog/national-indicators/alignments/<int:link_id>/archive/",
        views.indicator_alignment_archive,
        name="indicator_alignment_archive",
    ),
    path(
        "catalog/national-indicators/<uuid:indicator_uuid>/methodologies/",
        views.indicator_methodology_versions,
        name="indicator_methodologies",
    ),
    path(
        "catalog/national-indicators/methodologies/<int:link_id>/archive/",
        views.indicator_methodology_archive,
        name="indicator_methodology_archive",
    ),
    path("evidence/", views.evidence_list, name="evidence_list"),
    path("evidence/new/", views.evidence_create, name="evidence_create"),
    path("evidence/<uuid:evidence_uuid>/", views.evidence_detail, name="evidence_detail"),
    path("evidence/<uuid:evidence_uuid>/edit/", views.evidence_edit, name="evidence_edit"),
    path("datasets/", views.dataset_list, name="dataset_list"),
    path("datasets/new/", views.dataset_create, name="dataset_create"),
    path("datasets/<uuid:dataset_uuid>/", views.dataset_detail, name="dataset_detail"),
    path("datasets/<uuid:dataset_uuid>/edit/", views.dataset_edit, name="dataset_edit"),
    path("catalog/monitoring-programmes/", views.monitoring_programme_list, name="monitoring_programme_list"),
    path(
        "catalog/monitoring-programmes/new/",
        views.monitoring_programme_create,
        name="monitoring_programme_create",
    ),
    path(
        "catalog/monitoring-programmes/<uuid:programme_uuid>/",
        views.monitoring_programme_detail,
        name="monitoring_programme_detail",
    ),
    path(
        "catalog/monitoring-programmes/<uuid:programme_uuid>/edit/",
        views.monitoring_programme_edit,
        name="monitoring_programme_edit",
    ),
    path("catalog/methodologies/", views.methodology_list, name="methodology_list"),
    path("catalog/methodologies/new/", views.methodology_create, name="methodology_create"),
    path("catalog/methodologies/<uuid:methodology_uuid>/", views.methodology_detail, name="methodology_detail"),
    path(
        "catalog/methodologies/<uuid:methodology_uuid>/edit/",
        views.methodology_edit,
        name="methodology_edit",
    ),
    path("catalog/methodology-versions/", views.methodology_version_list, name="methodology_version_list"),
    path(
        "catalog/methodology-versions/<uuid:version_uuid>/",
        views.methodology_version_detail,
        name="methodology_version_detail",
    ),
    path(
        "catalog/methodology-versions/new/",
        views.methodology_version_create,
        name="methodology_version_create",
    ),
    path(
        "catalog/methodology-versions/<uuid:version_uuid>/edit/",
        views.methodology_version_edit,
        name="methodology_version_edit",
    ),
    path("catalog/data-agreements/", views.data_agreement_list, name="data_agreement_list"),
    path("catalog/data-agreements/new/", views.data_agreement_create, name="data_agreement_create"),
    path(
        "catalog/data-agreements/<uuid:agreement_uuid>/",
        views.data_agreement_detail,
        name="data_agreement_detail",
    ),
    path(
        "catalog/data-agreements/<uuid:agreement_uuid>/edit/",
        views.data_agreement_edit,
        name="data_agreement_edit",
    ),
    path("catalog/sensitivity-classes/", views.sensitivity_class_list, name="sensitivity_class_list"),
    path("catalog/sensitivity-classes/new/", views.sensitivity_class_create, name="sensitivity_class_create"),
    path(
        "catalog/sensitivity-classes/<uuid:class_uuid>/",
        views.sensitivity_class_detail,
        name="sensitivity_class_detail",
    ),
    path(
        "catalog/sensitivity-classes/<uuid:class_uuid>/edit/",
        views.sensitivity_class_edit,
        name="sensitivity_class_edit",
    ),
    path("catalog/frameworks/", views.framework_list, name="catalog_framework_list"),
    path("catalog/frameworks/new/", views.framework_create, name="framework_create"),
    path("catalog/frameworks/<uuid:framework_uuid>/edit/", views.framework_edit, name="framework_edit"),
    path("catalog/frameworks/<uuid:framework_uuid>/archive/", views.framework_archive, name="framework_archive"),
    path("catalog/framework-goals/", views.framework_goal_list, name="catalog_framework_goal_list"),
    path("catalog/framework-goals/new/", views.framework_goal_create, name="framework_goal_create"),
    path("catalog/framework-goals/<uuid:goal_uuid>/edit/", views.framework_goal_edit, name="framework_goal_edit"),
    path("catalog/framework-goals/<uuid:goal_uuid>/archive/", views.framework_goal_archive, name="framework_goal_archive"),
    path("catalog/framework-targets/", views.framework_target_list, name="catalog_framework_target_list"),
    path("catalog/framework-targets/new/", views.framework_target_create, name="framework_target_create"),
    path("catalog/framework-targets/<uuid:target_uuid>/edit/", views.framework_target_edit, name="framework_target_edit"),
    path("catalog/framework-targets/<uuid:target_uuid>/archive/", views.framework_target_archive, name="framework_target_archive"),
    path("catalog/framework-indicators/", views.framework_indicator_list, name="catalog_framework_indicator_list"),
    path("catalog/framework-indicators/new/", views.framework_indicator_create, name="framework_indicator_create"),
    path("catalog/framework-indicators/<uuid:indicator_uuid>/edit/", views.framework_indicator_edit, name="framework_indicator_edit"),
    path(
        "catalog/framework-indicators/<uuid:indicator_uuid>/archive/",
        views.framework_indicator_archive,
        name="framework_indicator_archive",
    ),
    path("frameworks/", views.framework_list, name="framework_list"),
    path("frameworks/<uuid:framework_uuid>/", views.framework_detail, name="framework_detail"),
    path("framework-goals/", views.framework_goal_list, name="framework_goal_list"),
    path("framework-goals/<uuid:goal_uuid>/", views.framework_goal_detail, name="framework_goal_detail"),
    path("framework-targets/", views.framework_target_list, name="framework_target_list"),
    path("framework-targets/<uuid:target_uuid>/", views.framework_target_detail, name="framework_target_detail"),
    path("framework-indicators/", views.framework_indicator_list, name="framework_indicator_list"),
    path(
        "framework-indicators/<uuid:indicator_uuid>/",
        views.framework_indicator_detail,
        name="framework_indicator_detail",
    ),
    path("exports/", views.export_package_list, name="export_package_list"),
    path("exports/new/", views.export_package_create, name="export_package_create"),
    path("exports/<uuid:package_uuid>/", views.export_package_detail, name="export_package_detail"),
    path(
        "exports/<uuid:package_uuid>/download/",
        views.export_package_download,
        name="export_package_download",
    ),
    path(
        "exports/instances/<uuid:instance_uuid>/ort-nr7-narrative.json",
        views.export_ort_nr7_narrative_instance,
        name="export_ort_nr7_narrative_instance",
    ),
    path(
        "exports/instances/<uuid:instance_uuid>/ort-nr7-v2.json",
        views.export_ort_nr7_v2_instance,
        name="export_ort_nr7_v2_instance",
    ),
    path(
        "exports/<uuid:package_uuid>/<str:action>/",
        views.export_package_action,
        name="export_package_action",
    ),
    path("reporting/cycles/", views.reporting_cycle_list, name="reporting_cycle_list"),
    path("reporting/cycles/new/", views.reporting_cycle_create, name="reporting_cycle_create"),
    path("reporting/cycles/<uuid:cycle_uuid>/", views.reporting_cycle_detail, name="reporting_cycle_detail"),
    path("reporting/instances/new/", views.reporting_instance_create, name="reporting_instance_create"),
    path(
        "reporting/instances/<uuid:instance_uuid>/",
        views.reporting_instance_detail,
        name="reporting_instance_detail",
    ),
    path(
        "reporting/set-current/<uuid:instance_uuid>/",
        views.reporting_set_current_instance,
        name="reporting_set_current_instance",
    ),
    path(
        "reporting/clear-current/",
        views.reporting_clear_current_instance,
        name="reporting_clear_current_instance",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/sections/",
        views.reporting_instance_sections,
        name="reporting_instance_sections",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/section-i/",
        views.reporting_instance_section_i,
        name="reporting_instance_section_i",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/section-ii/",
        views.reporting_instance_section_ii,
        name="reporting_instance_section_ii",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/sections/<str:section_code>/edit/",
        views.reporting_instance_section_edit,
        name="reporting_instance_section_edit",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/sections/<str:section_code>/preview/",
        views.reporting_instance_section_preview,
        name="reporting_instance_section_preview",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/section-iii/",
        views.reporting_instance_section_iii,
        name="reporting_instance_section_iii",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/section-iii/<uuid:target_uuid>/",
        views.reporting_instance_section_iii_edit,
        name="reporting_instance_section_iii_edit",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/section-iv/",
        views.reporting_instance_section_iv,
        name="reporting_instance_section_iv",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/section-iv/goals/",
        views.reporting_instance_section_iv_goals,
        name="reporting_instance_section_iv_goals",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/section-iv/goals/<uuid:goal_uuid>/",
        views.reporting_instance_section_iv_goal_edit,
        name="reporting_instance_section_iv_goal_edit",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/section-iv/binary-indicators/",
        views.reporting_instance_section_iv_binary_indicators,
        name="reporting_instance_section_iv_binary_indicators",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/section-iv/<uuid:framework_target_uuid>/",
        views.reporting_instance_section_iv_edit,
        name="reporting_instance_section_iv_edit",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/section-v/",
        views.reporting_instance_section_v,
        name="reporting_instance_section_v",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/approvals/",
        views.reporting_instance_approvals,
        name="reporting_instance_approvals",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/approvals/bulk/",
        views.reporting_instance_approval_bulk,
        name="reporting_instance_approval_bulk",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/approvals/<str:obj_type>/<uuid:obj_uuid>/<str:action>/",
        views.reporting_instance_approval_action,
        name="reporting_instance_approval_action",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/consent/",
        views.reporting_instance_consent,
        name="reporting_instance_consent",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/consent/<str:obj_type>/<uuid:obj_uuid>/<str:action>/",
        views.reporting_instance_consent_action,
        name="reporting_instance_consent_action",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/freeze/",
        views.reporting_instance_freeze,
        name="reporting_instance_freeze",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/report-pack/",
        views.reporting_instance_report_pack,
        name="reporting_instance_report_pack",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/review/",
        views.reporting_instance_review,
        name="reporting_instance_review",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/alignment-coverage/",
        views.reporting_instance_alignment_coverage,
        name="reporting_instance_alignment_coverage",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/alignment/orphans/national-targets/",
        views_alignment_bulk.alignment_orphans_targets,
        name="alignment_orphans_targets",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/alignment/orphans/indicators/",
        views_alignment_bulk.alignment_orphans_indicators,
        name="alignment_orphans_indicators",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/alignment/mappings/",
        views_alignment_bulk.alignment_mappings_manage,
        name="alignment_mappings_manage",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/review-pack-v2/",
        views.reporting_instance_review_pack_v2,
        name="reporting_instance_review_pack_v2",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/review-decisions/",
        views.reporting_instance_review_decisions,
        name="reporting_instance_review_decisions",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/review-decisions/create/",
        views.reporting_instance_review_decision_create,
        name="reporting_instance_review_decision_create",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/snapshots/",
        views.reporting_instance_snapshots,
        name="reporting_instance_snapshots",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/snapshots/create/",
        views.reporting_instance_snapshot_create,
        name="reporting_instance_snapshot_create",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/snapshots/diff/",
        views.reporting_instance_snapshot_diff,
        name="reporting_instance_snapshot_diff",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/snapshots/<uuid:snapshot_uuid>/",
        views.reporting_instance_snapshot_detail,
        name="reporting_instance_snapshot_detail",
    ),
    path(
        "reporting/instances/<uuid:instance_uuid>/snapshots/<uuid:snapshot_uuid>/download.json",
        views.reporting_instance_snapshot_download,
        name="reporting_instance_snapshot_download",
    ),
    path("manage/review-queue/", views.review_queue, name="review_queue"),
    path("manage/review-queue/<str:obj_type>/<uuid:obj_uuid>/", views.review_detail, name="review_detail"),
    path(
        "manage/review-queue/<str:obj_type>/<uuid:obj_uuid>/<str:action>/",
        views.review_action,
        name="review_action",
    ),
    path("manage/audit-events/", views_audit.audit_event_list, name="audit_event_list"),
    path("notifications/", views_notifications.notification_list, name="notification_list"),
    path("metrics/", views_metrics.metrics, name="metrics"),
]
